version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: training
    volumes:
    - ./seed.development.sql:/docker-entrypoint-initdb.d/postgres_seed.sql

  server: 
    build: ./server
    ports: 
      - 4000:4000
    volumes: 
      - ./server:/app
    environment: 
      PGHOST: 'postgres'
      PGUSER: docker
      PGPASSWORD: docker
      PGDATABASE: training

  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
