version: '3.7'
services:
  server: 
    build: ./server
    ports: 
      - 4000:4000
    volumes: 
      - ./server:/app

  client: 
    build: ./client
    ports: 
      -3000:3000
    volumes: 
     - ./client:/app